apiVersion: apps/v1
kind: Deployment
metadata: 
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 1 #1 pod is enough for local
  selector: 
    matchLabels:
      app: go-app
  template: 
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: go-api #tilt automatically manage this
        ports:
        - containerPort: 8080
        env: 
        - name: ENV
          value: "local"
          #cloud sql connection skip in local
          
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits: 
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5 
          periodSeconds: 10
---
apiVersion: v1
kind: service
metadata: 
  name: go-app-service
spec: 
  type: ClusterIP #for local cluster IP is enough (tilt do port forwarding)
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 80    
    targetPort: 8080 